# Generated by Django 5.1 on 2024-09-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('clolor', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('grey', 'Grey'), ('violet', 'Violet')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
